language: c

script: printenv && grep flbf /usr/include/*h && uname -a && /bin/sh ./bin/setup.sh && cd build && sh -x ../configure --enable-warnings && make && sudo make install && make test

notifications:
  recipients:
    - libslax-noise@googlegroups.com

branches:
  only:
    - master
    - develop
