language: c

script: printenv && cat /usr/include/stdio_ext.h && uname -a && /bin/sh ./bin/setup.sh && cd build && ../configure --enable-warnings && make && sudo make install && make test

notifications:
  recipients:
    - libslax-noise@googlegroups.com

branches:
  only:
    - master
    - develop
